name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build and run Docker Compose with tests
      run: |
        chmod +x exec.sh
        ./exec.sh
      env:
        DOCKER_BUILDKIT: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Pull latest Docker images
      run: docker-compose pull

    - name: Deploy with Docker Compose
      run: |
        docker-compose up -d
        sleep 30  # Wait for services to start

    - name: Verify Kong
      run: |
        docker-compose exec -T kong kong health
        curl -I http://localhost:8001 || echo "Kong Admin API is not accessible"
        curl -I http://localhost:8000 || echo "Kong Proxy is not accessible"

    - name: Verify Keycloak
      run: |
        curl -I http://localhost:8180 || echo "Keycloak is not accessible"

    - name: Verify Konga
      run: |
        curl -I http://localhost:1337 || echo "Konga is not accessible"

    - name: Verify Prometheus
      run: |
        curl -I http://localhost:9090 || echo "Prometheus is not accessible"

    - name: Verify Grafana
      run: |
        curl -I http://localhost:3000 || echo "Grafana is not accessible"

  cleanup-environment:
    runs-on: ubuntu-latest
    if: always()
    steps:
    - name: Cleanup Docker environment
      run: |
        docker-compose down
        docker system prune -af
