name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build and start services with Docker Compose
      run: docker-compose up -d --build

    - name: Wait for services to be ready
      run: |
        echo "Waiting for services to be ready..."
        sleep 30 # Attends 30 secondes pour que les services soient prêts

    - name: Run tests
      run: |
        # Ici tu peux exécuter tes tests spécifiques, par exemple:
        # docker-compose exec <service-name> <test-command>
        echo "Running tests..."
        # Exemple:
        # docker-compose exec kong curl -s http://localhost:8000 | grep 'kong'

    - name: Shut down services
      run: docker-compose down